import { PDFDocument, StandardFonts, rgb, PDFPage, PDFFont } from 'pdf-lib';
import {
  ExecutiveSummaryData,
  BusinessSummaryData,
  LegalSummaryData,
  RiskAnalysis,
  ReportType
} from '../types/contractTypes';

const COLORS = {
  primary: rgb(0.42, 0.36, 0.91),      // Indigo
  secondary: rgb(0.13, 0.71, 0.78),    // Cyan
  dark: rgb(0.06, 0.07, 0.10),
  text: rgb(0.12, 0.14, 0.18),
  textMuted: rgb(0.42, 0.45, 0.52),
  border: rgb(0.85, 0.86, 0.90),
  success: rgb(0.10, 0.65, 0.42),
  warning: rgb(0.95, 0.62, 0.10),
  danger: rgb(0.86, 0.18, 0.20),
  critical: rgb(0.66, 0.10, 0.13),
  pageBg: rgb(0.98, 0.98, 0.99),
  panelBg: rgb(0.95, 0.96, 0.98)
};

interface PdfBuilderContext {
  doc: PDFDocument;
  page: PDFPage;
  font: PDFFont;
  fontBold: PDFFont;
  fontItalic: PDFFont;
  cursorY: number;
  pageNum: number;
  totalPages: number;
  pageWidth: number;
  pageHeight: number;
  marginX: number;
}

function riskColor(score: number) {
  if (score >= 81) return COLORS.critical;
  if (score >= 61) return COLORS.danger;
  if (score >= 41) return COLORS.warning;
  if (score >= 21) return COLORS.secondary;
  return COLORS.success;
}

function riskLevelColor(level: string) {
  switch (level) {
    case 'Critical': return COLORS.critical;
    case 'High': return COLORS.danger;
    case 'Moderate': return COLORS.warning;
    case 'Low': return COLORS.secondary;
    case 'Very Low': return COLORS.success;
    default: return COLORS.textMuted;
  }
}

function wrapText(text: string, font: PDFFont, fontSize: number, maxWidth: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let current = '';

  for (const word of words) {
    const test = current ? `${current} ${word}` : word;
    const width = font.widthOfTextAtSize(test, fontSize);
    if (width > maxWidth && current) {
      lines.push(current);
      current = word;
    } else {
      current = test;
    }
  }
  if (current) lines.push(current);
  return lines;
}

function newPage(ctx: PdfBuilderContext): void {
  ctx.page = ctx.doc.addPage([ctx.pageWidth, ctx.pageHeight]);
  ctx.cursorY = ctx.pageHeight - 60;
  ctx.pageNum++;
  drawHeader(ctx);
  drawFooter(ctx);
}

function drawHeader(ctx: PdfBuilderContext): void {
  const { page, font, fontBold, pageWidth } = ctx;
  // Header band
  page.drawRectangle({
    x: 0,
    y: page.getHeight() - 30,
    width: pageWidth,
    height: 30,
    color: COLORS.primary
  });
  page.drawText('JurisAI', {
    x: 40,
    y: page.getHeight() - 20,
    size: 11,
    font: fontBold,
    color: rgb(1, 1, 1)
  });
  page.drawText('Executive Intelligence Report', {
    x: 95,
    y: page.getHeight() - 20,
    size: 9,
    font,
    color: rgb(1, 1, 1)
  });
  page.drawText('CONFIDENTIAL', {
    x: pageWidth - 110,
    y: page.getHeight() - 20,
    size: 8,
    font: fontBold,
    color: rgb(1, 1, 1)
  });
}

function drawFooter(ctx: PdfBuilderContext): void {
  const { page, font, pageWidth, pageHeight, pageNum, totalPages } = ctx;
  page.drawText('Generated by JurisAI', {
    x: 40,
    y: 25,
    size: 8,
    font,
    color: COLORS.textMuted
  });
  page.drawText(`Page ${pageNum} of ${totalPages}`, {
    x: pageWidth - 90,
    y: 25,
    size: 8,
    font,
    color: COLORS.textMuted
  });
  page.drawLine({
    start: { x: 40, y: 40 },
    end: { x: pageWidth - 40, y: 40 },
    thickness: 0.5,
    color: COLORS.border
  });
}

function ensureSpace(ctx: PdfBuilderContext, requiredHeight: number): void {
  if (ctx.cursorY - requiredHeight < 70) {
    newPage(ctx);
  }
}

function drawSectionHeading(ctx: PdfBuilderContext, text: string): void {
  ensureSpace(ctx, 50);
  const { page, fontBold, font, marginX, pageWidth, cursorY } = ctx;
  page.drawText(text.toUpperCase(), {
    x: marginX,
    y: cursorY - 16,
    size: 12,
    font: fontBold,
    color: COLORS.primary
  });
  page.drawText('—'.repeat(60), {
    x: marginX,
    y: cursorY - 22,
    size: 8,
    font,
    color: COLORS.border
  });
  ctx.cursorY -= 30;
}

function drawParagraph(ctx: PdfBuilderContext, text: string, options: { fontSize?: number; bold?: boolean; color?: any; indent?: number; spacing?: number } = {}): void {
  const { fontSize = 10, bold = false, color = COLORS.text, indent = 0, spacing = 4 } = options;
  const font = bold ? ctx.fontBold : ctx.font;
  const maxWidth = ctx.pageWidth - 2 * ctx.marginX - indent;
  const lines = wrapText(text, font, fontSize, maxWidth);

  for (const line of lines) {
    ensureSpace(ctx, fontSize + 4);
    ctx.page.drawText(line, {
      x: ctx.marginX + indent,
      y: ctx.cursorY - fontSize,
      size: fontSize,
      font,
      color
    });
    ctx.cursorY -= fontSize + 2;
  }
  ctx.cursorY -= spacing;
}

function drawBulletList(ctx: PdfBuilderContext, items: string[]): void {
  for (const item of items) {
    if (!item) continue;
    ensureSpace(ctx, 18);
    const maxWidth = ctx.pageWidth - 2 * ctx.marginX - 18;
    const lines = wrapText(item, ctx.font, 10, maxWidth);
    ctx.page.drawText('•', {
      x: ctx.marginX,
      y: ctx.cursorY - 10,
      size: 12,
      font: ctx.fontBold,
      color: COLORS.primary
    });
    for (let i = 0; i < lines.length; i++) {
      if (i > 0) ensureSpace(ctx, 14);
      ctx.page.drawText(lines[i], {
        x: ctx.marginX + 14,
        y: ctx.cursorY - 10,
        size: 10,
        font: ctx.font,
        color: COLORS.text
      });
      ctx.cursorY -= 14;
    }
    ctx.cursorY -= 2;
  }
}

function drawPanel(ctx: PdfBuilderContext, title: string, content: () => void): void {
  ensureSpace(ctx, 40);
  const panelX = ctx.marginX;
  const panelWidth = ctx.pageWidth - 2 * ctx.marginX;
  const startY = ctx.cursorY;

  // Title bar
  ctx.page.drawRectangle({
    x: panelX,
    y: startY - 8,
    width: panelWidth,
    height: 24,
    color: COLORS.primary
  });
  ctx.page.drawText(title, {
    x: panelX + 12,
    y: startY - 2,
    size: 10,
    font: ctx.fontBold,
    color: rgb(1, 1, 1)
  });
  ctx.cursorY -= 28;

  const beforeContent = ctx.cursorY;
  content();
  const afterContent = ctx.cursorY;

  // Background fill
  ctx.page.drawRectangle({
    x: panelX,
    y: afterContent + 4,
    width: panelWidth,
    height: beforeContent - afterContent + 4,
    color: COLORS.panelBg,
    opacity: 0.5
  });

  // Border
  ctx.page.drawRectangle({
    x: panelX,
    y: afterContent + 4,
    width: panelWidth,
    height: beforeContent - afterContent + 4,
    borderColor: COLORS.border,
    borderWidth: 0.5
  });

  ctx.cursorY -= 12;
}

function drawCoverPage(ctx: PdfBuilderContext, reportType: ReportType, contractName: string, generatedAt: string, riskAnalysis: RiskAnalysis | null): void {
  const { page, pageWidth, pageHeight, font, fontBold, fontItalic } = ctx;

  // Background gradient effect using rectangles
  page.drawRectangle({
    x: 0,
    y: 0,
    width: pageWidth,
    height: pageHeight,
    color: COLORS.dark
  });

  // Accent bar
  page.drawRectangle({
    x: 0,
    y: pageHeight - 12,
    width: pageWidth,
    height: 12,
    color: COLORS.primary
  });
  page.drawRectangle({
    x: 0,
    y: 0,
    width: pageWidth,
    height: 8,
    color: COLORS.secondary
  });

  // Branding
  page.drawText('JurisAI', {
    x: 60,
    y: pageHeight - 90,
    size: 36,
    font: fontBold,
    color: rgb(1, 1, 1)
  });
  page.drawText('Executive Intelligence', {
    x: 60,
    y: pageHeight - 120,
    size: 18,
    font: fontBold,
    color: COLORS.secondary
  });
  page.drawText('Reporting System', {
    x: 60,
    y: pageHeight - 138,
    size: 14,
    font: fontItalic,
    color: rgb(0.75, 0.78, 0.85)
  });

  // Divider
  page.drawRectangle({
    x: 60,
    y: pageHeight - 165,
    width: 80,
    height: 3,
    color: COLORS.primary
  });

  // Report type tag
  const typeLabels: Record<ReportType, string> = {
    executive: 'EXECUTIVE BRIEFING',
    business: 'BUSINESS BRIEFING',
    legal: 'LEGAL BRIEFING',
    full: 'COMPREHENSIVE BRIEFING'
  };
  page.drawText(typeLabels[reportType], {
    x: 60,
    y: pageHeight - 200,
    size: 12,
    font: fontBold,
    color: COLORS.secondary
  });

  // Contract name
  const nameLines = wrapText(contractName, fontBold, 28, pageWidth - 120);
  let nameY = pageHeight - 240;
  for (const line of nameLines) {
    page.drawText(line, {
      x: 60,
      y: nameY,
      size: 28,
      font: fontBold,
      color: rgb(1, 1, 1)
    });
    nameY -= 34;
  }

  // Generated date
  const dateText = `Report generated on ${generatedAt}`;
  page.drawText(dateText, {
    x: 60,
    y: 100,
    size: 11,
    font: fontItalic,
    color: rgb(0.75, 0.78, 0.85)
  });

  // Risk score panel
  if (riskAnalysis) {
    const panelX = 60;
    const panelY = 130;
    const panelW = 240;
    const panelH = 60;

    page.drawRectangle({
      x: panelX,
      y: panelY,
      width: panelW,
      height: panelH,
      color: rgb(0.12, 0.14, 0.22)
    });
    page.drawRectangle({
      x: panelX,
      y: panelY,
      width: panelW,
      height: panelH,
      borderColor: COLORS.primary,
      borderWidth: 1
    });

    page.drawText('OVERALL RISK', {
      x: panelX + 14,
      y: panelY + panelH - 16,
      size: 8,
      font: fontBold,
      color: rgb(0.65, 0.68, 0.75)
    });
    page.drawText(`${riskAnalysis.overallRiskScore} / 100`, {
      x: panelX + 14,
      y: panelY + 16,
      size: 22,
      font: fontBold,
      color: riskColor(riskAnalysis.overallRiskScore)
    });
    page.drawText(riskAnalysis.riskLevel.toUpperCase(), {
      x: panelX + 130,
      y: panelY + 26,
      size: 14,
      font: fontBold,
      color: riskLevelColor(riskAnalysis.riskLevel)
    });
  }

  // Footer brand
  page.drawText('jurisai.app', {
    x: 60,
    y: 50,
    size: 10,
    font: fontBold,
    color: COLORS.secondary
  });
  page.drawText('AI-Powered Contract Intelligence', {
    x: 60,
    y: 36,
    size: 8,
    font: fontItalic,
    color: rgb(0.55, 0.58, 0.65)
  });
}

function drawExecutiveOverviewPanel(ctx: PdfBuilderContext, summary: ExecutiveSummaryData): void {
  drawSectionHeading(ctx, '1. Contract Overview');

  // Two-column key-value grid
  const colWidth = (ctx.pageWidth - 2 * ctx.marginX - 20) / 2;
  const rows: { label: string; value: string }[] = [
    { label: 'Contract Type', value: summary.contractType },
    { label: 'Duration', value: summary.duration },
    { label: 'Effective Date', value: summary.effectiveDate || 'Not specified' },
    { label: 'Expiration Date', value: summary.expirationDate || 'Not specified' },
    { label: 'Vendor', value: summary.parties.vendor },
    { label: 'Customer', value: summary.parties.customer }
  ];

  for (let i = 0; i < rows.length; i += 2) {
    ensureSpace(ctx, 28);
    const y = ctx.cursorY - 8;
    const left = rows[i];
    const right = rows[i + 1];
    ctx.page.drawText(left.label.toUpperCase(), {
      x: ctx.marginX,
      y: y,
      size: 7,
      font: ctx.fontBold,
      color: COLORS.textMuted
    });
    ctx.page.drawText(left.value, {
      x: ctx.marginX,
      y: y - 12,
      size: 10,
      font: ctx.fontBold,
      color: COLORS.text
    });
    if (right) {
      ctx.page.drawText(right.label.toUpperCase(), {
        x: ctx.marginX + colWidth + 20,
        y: y,
        size: 7,
        font: ctx.fontBold,
        color: COLORS.textMuted
      });
      ctx.page.drawText(right.value, {
        x: ctx.marginX + colWidth + 20,
        y: y - 12,
        size: 10,
        font: ctx.fontBold,
        color: COLORS.text
      });
    }
    ctx.cursorY -= 30;
  }

  ctx.cursorY -= 4;
  drawParagraph(ctx, 'CONTRACT PURPOSE', { fontSize: 8, bold: true, color: COLORS.textMuted, spacing: 2 });
  drawParagraph(ctx, summary.contractPurpose, { fontSize: 10 });
}

function drawRiskGauge(ctx: PdfBuilderContext, score: number, level: string): void {
  ensureSpace(ctx, 70);
  const cx = ctx.marginX + 50;
  const cy = ctx.cursorY - 50;
  const r = 32;

  // Background ring
  for (let i = 0; i < 360; i += 5) {
    const rad = (i * Math.PI) / 180;
    const x1 = cx + r * Math.cos(rad);
    const y1 = cy + r * Math.sin(rad);
    const x2 = cx + (r + 4) * Math.cos(rad);
    const y2 = cy + (r + 4) * Math.sin(rad);
    ctx.page.drawLine({
      start: { x: x1, y: y1 },
      end: { x: x2, y: y2 },
      thickness: 2,
      color: COLORS.border
    });
  }

  // Filled arc
  const fillDeg = (score / 100) * 360;
  for (let i = 0; i < fillDeg; i += 5) {
    const rad = (i * Math.PI) / 180;
    const x1 = cx + r * Math.cos(rad);
    const y1 = cy + r * Math.sin(rad);
    const x2 = cx + (r + 4) * Math.cos(rad);
    const y2 = cy + (r + 4) * Math.sin(rad);
    ctx.page.drawLine({
      start: { x: x1, y: y1 },
      end: { x: x2, y: y2 },
      thickness: 2,
      color: riskColor(score)
    });
  }

  // Center text
  ctx.page.drawText(String(score), {
    x: cx - 12,
    y: cy + 2,
    size: 18,
    font: ctx.fontBold,
    color: COLORS.text
  });
  ctx.page.drawText('/ 100', {
    x: cx - 8,
    y: cy - 12,
    size: 8,
    font: ctx.font,
    color: COLORS.textMuted
  });
  ctx.page.drawText(level.toUpperCase() + ' RISK', {
    x: cx - 28,
    y: cy - 26,
    size: 8,
    font: ctx.fontBold,
    color: riskLevelColor(level)
  });

  // Move cursor
  ctx.cursorY -= 80;
}

function drawRiskBreakdownBars(ctx: PdfBuilderContext, breakdown: { Financial: number; Legal: number; Operational: number; Reputational: number }): void {
  ensureSpace(ctx, 90);
  const startX = ctx.marginX + 130;
  const barMaxWidth = ctx.pageWidth - ctx.marginX - startX - 20;
  const labels: { key: keyof typeof breakdown; label: string }[] = [
    { key: 'Financial', label: 'Financial' },
    { key: 'Legal', label: 'Legal' },
    { key: 'Operational', label: 'Operational' },
    { key: 'Reputational', label: 'Reputational' }
  ];

  for (const { key, label } of labels) {
    const score = breakdown[key];
    const w = (score / 100) * barMaxWidth;
    const y = ctx.cursorY - 8;
    ctx.page.drawText(label, {
      x: ctx.marginX + 130,
      y: y,
      size: 9,
      font: ctx.font,
      color: COLORS.text
    });
    ctx.page.drawRectangle({
      x: ctx.marginX + 200,
      y: y - 2,
      width: barMaxWidth,
      height: 8,
      color: COLORS.panelBg
    });
    if (w > 0) {
      ctx.page.drawRectangle({
        x: ctx.marginX + 200,
        y: y - 2,
        width: w,
        height: 8,
        color: riskColor(score)
      });
    }
    ctx.page.drawText(String(score), {
      x: ctx.marginX + 200 + barMaxWidth + 6,
      y: y,
      size: 9,
      font: ctx.fontBold,
      color: riskColor(score)
    });
    ctx.cursorY -= 14;
  }
  ctx.cursorY -= 6;
}

export interface ReportInput {
  reportType: ReportType;
  contractName: string;
  generatedAt: string;
  executive?: ExecutiveSummaryData | null;
  business?: BusinessSummaryData | null;
  legal?: LegalSummaryData | null;
  riskAnalysis: RiskAnalysis | null;
}

export async function generatePdfReport(input: ReportInput): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  doc.setTitle(`${input.contractName} — JurisAI Executive Report`);
  doc.setAuthor('JurisAI');
  doc.setSubject('Executive Intelligence Report');
  doc.setCreator('JurisAI Reporting Engine');

  const font = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);
  const fontItalic = await doc.embedFont(StandardFonts.HelveticaOblique);

  const A4_WIDTH = 595.28;
  const A4_HEIGHT = 841.89;

  // Cover page (no header/footer)
  const coverPage = doc.addPage([A4_WIDTH, A4_HEIGHT]);
  const coverCtx: PdfBuilderContext = {
    doc,
    page: coverPage,
    font,
    fontBold,
    fontItalic,
    cursorY: A4_HEIGHT - 60,
    pageNum: 0,
    totalPages: 0,
    pageWidth: A4_WIDTH,
    pageHeight: A4_HEIGHT,
    marginX: 60
  };
  drawCoverPage(coverCtx, input.reportType, input.contractName, input.generatedAt, input.riskAnalysis);

  // First content page
  const firstPage = doc.addPage([A4_WIDTH, A4_HEIGHT]);
  const ctx: PdfBuilderContext = {
    doc,
    page: firstPage,
    font,
    fontBold,
    fontItalic,
    cursorY: A4_HEIGHT - 60,
    pageNum: 1,
    totalPages: 1,
    pageWidth: A4_WIDTH,
    pageHeight: A4_HEIGHT,
    marginX: 60
  };
  drawHeader(ctx);
  drawFooter(ctx);

  // === Section: Executive Summary (always render if executive present or reportType is full) ===
  if (input.executive && (input.reportType === 'executive' || input.reportType === 'full')) {
    const ex = input.executive;
    drawSectionHeading(ctx, 'Executive Summary');
    drawParagraph(ctx, ex.contractPurpose, { fontSize: 11, spacing: 6 });

    // Risk overview
    drawSectionHeading(ctx, '2. Risk Assessment');
    // Two-column: gauge on left, bars on right
    const sectionStartY = ctx.cursorY;
    drawRiskGauge(ctx, ex.overallRiskScore, ex.riskLevel);
    drawRiskBreakdownBars(ctx, ex.riskDistribution);
    // Risk allocation
    ctx.cursorY = sectionStartY - 90;
    drawParagraph(ctx, 'Risk Allocation', { fontSize: 9, bold: true, color: COLORS.textMuted, spacing: 2 });
    drawParagraph(ctx, ex.riskAllocation, { fontSize: 10 });
  }

  // === Section: Contract Overview ===
  if (input.executive && (input.reportType === 'executive' || input.reportType === 'full')) {
    drawSectionHeading(ctx, '3. Contract Overview & Parties');
    drawParagraph(ctx, 'CONTRACT TYPE', { fontSize: 8, bold: true, color: COLORS.textMuted, spacing: 2 });
    drawParagraph(ctx, input.executive.contractType, { fontSize: 11, bold: true });
    drawParagraph(ctx, 'DURATION', { fontSize: 8, bold: true, color: COLORS.textMuted, spacing: 2 });
    drawParagraph(ctx, input.executive.duration, { fontSize: 11 });
    if (input.executive.effectiveDate) {
      drawParagraph(ctx, 'EFFECTIVE DATE', { fontSize: 8, bold: true, color: COLORS.textMuted, spacing: 2 });
      drawParagraph(ctx, input.executive.effectiveDate, { fontSize: 10 });
    }
    if (input.executive.expirationDate) {
      drawParagraph(ctx, 'EXPIRATION DATE', { fontSize: 8, bold: true, color: COLORS.textMuted, spacing: 2 });
      drawParagraph(ctx, input.executive.expirationDate, { fontSize: 10 });
    }

    drawParagraph(ctx, 'PARTIES', { fontSize: 8, bold: true, color: COLORS.textMuted, spacing: 2 });
    drawParagraph(ctx, `Vendor: ${input.executive.parties.vendor}`, { fontSize: 10, bold: true });
    drawParagraph(ctx, `Customer: ${input.executive.parties.customer}`, { fontSize: 10, bold: true });
    for (const other of input.executive.parties.otherParties) {
      drawParagraph(ctx, `Other Party: ${other}`, { fontSize: 10 });
    }
  }

  // === Section: Key Commercial Terms ===
  if (input.executive && (input.reportType === 'executive' || input.reportType === 'full')) {
    drawSectionHeading(ctx, '4. Key Commercial Terms');
    if (input.executive.keyCommercialTerms.length === 0) {
      drawParagraph(ctx, 'No commercial terms could be extracted from the contract.', { fontSize: 10 });
    } else {
      for (const term of input.executive.keyCommercialTerms) {
        ensureSpace(ctx, 24);
        drawParagraph(ctx, term.label.toUpperCase(), { fontSize: 8, bold: true, color: COLORS.textMuted, spacing: 2 });
        drawParagraph(ctx, term.value, { fontSize: 10 });
      }
    }
  }

  // === Section: Important Obligations ===
  if (input.executive && (input.reportType === 'executive' || input.reportType === 'full')) {
    drawSectionHeading(ctx, '5. Important Obligations');
    const ob = input.executive.importantObligations;
    if (ob.vendor.length > 0) {
      drawParagraph(ctx, 'Vendor Obligations', { fontSize: 9, bold: true, color: COLORS.primary, spacing: 2 });
      drawBulletList(ctx, ob.vendor);
    }
    if (ob.customer.length > 0) {
      drawParagraph(ctx, 'Customer Obligations', { fontSize: 9, bold: true, color: COLORS.primary, spacing: 2 });
      drawBulletList(ctx, ob.customer);
    }
    if (ob.mutual.length > 0) {
      drawParagraph(ctx, 'Mutual Obligations', { fontSize: 9, bold: true, color: COLORS.primary, spacing: 2 });
      drawBulletList(ctx, ob.mutual);
    }
  }

  // === Section: Missing Protections ===
  if (input.executive && (input.reportType === 'executive' || input.reportType === 'full')) {
    drawSectionHeading(ctx, '6. Missing Protections');
    if (input.executive.missingProtections.length === 0) {
      drawParagraph(ctx, 'All standard protections are present in this contract.', { fontSize: 10, color: COLORS.success });
    } else {
      for (const m of input.executive.missingProtections) {
        ensureSpace(ctx, 40);
        drawParagraph(ctx, m.clauseType, { fontSize: 10, bold: true, color: COLORS.danger, spacing: 2 });
        drawParagraph(ctx, m.businessImpact, { fontSize: 10 });
      }
    }
  }

  // === Section: Top Negotiation Points ===
  if (input.executive && (input.reportType === 'executive' || input.reportType === 'full')) {
    drawSectionHeading(ctx, '7. Top Negotiation Points');
    if (input.executive.topNegotiationPoints.length === 0) {
      drawParagraph(ctx, 'No high-priority negotiation points identified.', { fontSize: 10 });
    } else {
      input.executive.topNegotiationPoints.forEach((p, i) => {
        ensureSpace(ctx, 60);
        drawParagraph(ctx, `${i + 1}. ${p.title}`, { fontSize: 11, bold: true, color: riskLevelColor(
          p.severity === 'Critical' ? 'Critical' : p.severity === 'High' ? 'High' : 'Moderate'
        ), spacing: 2 });
        drawParagraph(ctx, `Severity: ${p.severity}`, { fontSize: 8, bold: true, color: COLORS.textMuted, spacing: 2 });
        drawParagraph(ctx, `Why it matters: ${p.whyImportant}`, { fontSize: 10 });
        drawParagraph(ctx, `Potential impact: ${p.potentialImpact}`, { fontSize: 10, color: COLORS.danger });
      });
    }
  }

  // === Section: Recommended Next Steps ===
  if (input.executive && (input.reportType === 'executive' || input.reportType === 'full')) {
    drawSectionHeading(ctx, '8. Recommended Next Steps');
    if (input.executive.recommendedNextSteps.length === 0) {
      drawParagraph(ctx, 'No specific recommendations at this time.', { fontSize: 10 });
    } else {
      input.executive.recommendedNextSteps.forEach((r) => {
        ensureSpace(ctx, 40);
        const priorityColor = r.priority === 'Immediate' ? COLORS.critical : r.priority === 'High' ? COLORS.danger : r.priority === 'Medium' ? COLORS.warning : COLORS.secondary;
        drawParagraph(ctx, `[${r.priority.toUpperCase()}] ${r.title}`, { fontSize: 10, bold: true, color: priorityColor, spacing: 2 });
        drawParagraph(ctx, r.description, { fontSize: 10 });
      });
    }
  }

  // === Section: Business Summary ===
  if (input.business && (input.reportType === 'business' || input.reportType === 'full')) {
    newPage(ctx);
    const b = input.business;
    drawSectionHeading(ctx, 'Business Summary');
    drawParagraph(ctx, 'BUSINESS PURPOSE', { fontSize: 8, bold: true, color: COLORS.textMuted, spacing: 2 });
    drawParagraph(ctx, b.businessPurpose, { fontSize: 11 });
    drawParagraph(ctx, 'COMMERCIAL FOCUS', { fontSize: 8, bold: true, color: COLORS.textMuted, spacing: 2 });
    drawParagraph(ctx, b.commercialFocus, { fontSize: 11 });

    drawSectionHeading(ctx, 'Commercial Terms');
    const commercialRows = [
      { label: 'Payment Terms', value: b.paymentTerms },
      { label: 'Renewal Terms', value: b.renewalTerms },
      { label: 'Termination Notice', value: b.terminationNotice },
      { label: 'Service Commitments', value: b.serviceCommitments },
      { label: 'IP Ownership', value: b.ipOwnership }
    ];
    for (const r of commercialRows) {
      ensureSpace(ctx, 24);
      drawParagraph(ctx, r.label.toUpperCase(), { fontSize: 8, bold: true, color: COLORS.textMuted, spacing: 2 });
      drawParagraph(ctx, r.value, { fontSize: 10 });
    }

    drawSectionHeading(ctx, 'Business Impact');
    drawParagraph(ctx, 'FINANCIAL RISK', { fontSize: 8, bold: true, color: COLORS.textMuted, spacing: 2 });
    drawParagraph(ctx, b.financialRisk, { fontSize: 10 });
    drawParagraph(ctx, 'OPERATIONAL IMPACT', { fontSize: 8, bold: true, color: COLORS.textMuted, spacing: 2 });
    drawParagraph(ctx, b.operationalImpact, { fontSize: 10 });

    if (b.keyBenefits.length > 0) {
      drawParagraph(ctx, 'KEY BENEFITS', { fontSize: 9, bold: true, color: COLORS.success, spacing: 2 });
      drawBulletList(ctx, b.keyBenefits);
    }
    if (b.keyConcerns.length > 0) {
      drawParagraph(ctx, 'KEY CONCERNS', { fontSize: 9, bold: true, color: COLORS.danger, spacing: 2 });
      drawBulletList(ctx, b.keyConcerns);
    }
  }

  // === Section: Legal Summary ===
  if (input.legal && (input.reportType === 'legal' || input.reportType === 'full')) {
    newPage(ctx);
    const l = input.legal;
    drawSectionHeading(ctx, 'Legal Summary');
    drawParagraph(ctx, 'GOVERNING LAW', { fontSize: 8, bold: true, color: COLORS.textMuted, spacing: 2 });
    drawParagraph(ctx, l.governingLaw, { fontSize: 11 });

    const legalRows = [
      { label: 'Indemnification', value: l.indemnificationSummary },
      { label: 'Limitation of Liability', value: l.liabilitySummary },
      { label: 'Confidentiality', value: l.confidentialitySummary },
      { label: 'Intellectual Property', value: l.ipSummary },
      { label: 'Dispute Resolution', value: l.disputeResolutionSummary },
      { label: 'Force Majeure', value: l.forceMajeureStatus },
      { label: 'Data Protection', value: l.dataProtectionStatus }
    ];

    for (const r of legalRows) {
      ensureSpace(ctx, 40);
      drawSectionHeading(ctx, r.label);
      drawParagraph(ctx, r.value, { fontSize: 10 });
    }

    if (l.clauseLevelFindings.length > 0) {
      drawSectionHeading(ctx, 'Clause-Level Findings');
      for (const f of l.clauseLevelFindings) {
        ensureSpace(ctx, 40);
        const riskCol = riskLevelColor(f.riskLevel);
        drawParagraph(ctx, `[${f.clauseType}${f.sectionNumber ? ' § ' + f.sectionNumber : ''}] (${f.riskLevel})`, { fontSize: 10, bold: true, color: riskCol, spacing: 2 });
        drawParagraph(ctx, f.finding, { fontSize: 10 });
      }
    }

    if (l.criticalLegalRisks.length > 0) {
      drawSectionHeading(ctx, 'Critical Legal Risks');
      drawBulletList(ctx, l.criticalLegalRisks);
    }
  }

  // Update total page count footer
  const allPages = doc.getPages();
  ctx.totalPages = allPages.length;
  for (let i = 0; i < allPages.length; i++) {
    if (i === 0) continue; // Skip cover page
    const page = allPages[i];
    page.drawText(`Page ${i + 1} of ${allPages.length}`, {
      x: page.getWidth() - 90,
      y: 25,
      size: 8,
      font: ctx.font,
      color: COLORS.textMuted
    });
  }

  return await doc.save();
}
